@URL = http://localhost:3000

GET {{URL}}

###

GET {{URL}}/user

###

POST {{URL}}/user
Content-Type: application/json

{
  "id": 1,
  "name": "Marie Doe",
  "email": "mariedoe@example.com",
  "age": 19
}
